### ISSUE TITLE
Use default parameter values

### ISSUE THREAD

**Issue by Darkchove** [Tietokilta/ilmomasiina#108]
Instead of checking if a property exists in the configure function, you can use default parameter values to provide fallback values. This can make the code cleaner and more concise.

```js
export function configure({
  api = '/api',
  router,
  timezone = 'Europe/Helsinki',
}: IlmoConfig) {
  configureApi(api);
  if (router !== undefined) {
    configureRouter(router);
  }
  configuredTimezone = timezone;
}

```

**Comment by PurkkaKoodari** [comment]
This was probably written as is to allow partial and multiple configuration calls.

I agree that it might be cleaner that way, but if you wish to help with these trivial code style changes, please open a PR instead of multiple issues.
